import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:share_plus/share_plus.dart';
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';
import '../main.dart';

class BudgetScreen extends StatefulWidget {
  final AppState appState;

  const BudgetScreen({super.key, required this.appState});

  @override
  State<BudgetScreen> createState() => _BudgetScreenState();
}

class _BudgetScreenState extends State<BudgetScreen> with TickerProviderStateMixin {
  late AnimationController _fadeController;
  late Animation<double> _fadeAnimation;
  late Box _budgetBox;
  List<Map<String, dynamic>> _budgetItems = [];
  String? _filterCategory;
  final TextEditingController _itemController = TextEditingController();
  final TextEditingController _quantityController = TextEditingController();
  final TextEditingController _priceController = TextEditingController();
  String _selectedCategory = 'Materiales';
  double _autoGeneratedTotal = 0.0;

  @override
  void initState() {
    super.initState();
    _fadeController = AnimationController(vsync: this, duration: const Duration(milliseconds: 800));
    _fadeAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(CurvedAnimation(parent: _fadeController, curve: Curves.easeIn));
    _fadeController.forward();
    _initBudgetBox();
    if (kDebugMode) debugPrint("[TELEMETRIA BUDGET] Entrando a BudgetScreen PRO");
  }

  @override
  void dispose() {
    _fadeController.dispose();
    _itemController.dispose();
    _quantityController.dispose();
    _priceController.dispose();
    super.dispose();
  }

  Future<void> _initBudgetBox() async {
    _budgetBox = await Hive.openBox('budget_${widget.appState.currentUser?.uid ?? 'guest'}');
    _loadBudget();
  }

  void _loadBudget() {
    final rawBudget = _budgetBox.values.toList();
    _budgetItems = rawBudget.map((item) => Map<String, dynamic>.from(item)).toList();
    setState(() {});
  }

  void _addBudgetItem() {
    if (_itemController.text.isEmpty || _quantityController.text.isEmpty || _priceController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Completa todos los campos')),
      );
      return;
    }
    final quantity = double.tryParse(_quantityController.text) ?? 0;
    final price = double.tryParse(_priceController.text) ?? 0;
    final total = quantity * price;
    final newItem = {
      'item': _itemController.text,
      'quantity': quantity,
      'price': price,
      'total': total,
      'category': _selectedCategory,
      'date': DateTime.now(),
    };
    _budgetBox.add(newItem);
    _loadBudget();
    _clearFields();
    HapticFeedback.lightImpact();
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Item agregado')),
    );
  }

  void _clearFields() {
    _itemController.clear();
    _quantityController.clear();
    _priceController.clear();
    _selectedCategory = 'Materiales';
  }

  void _deleteBudgetItem(int index) {
    final originalIndex = _budgetItems.indexOf(_filteredItems[index]);
    _budgetBox.deleteAt(originalIndex);
    _loadBudget();
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Item eliminado')),
    );
  }

  List<Map<String, dynamic>> get _filteredItems {
    return _budgetItems.where((item) => _filterCategory == null || item['category'] == _filterCategory).toList();
  }

  double get _manualTotal {
    return _filteredItems.fold(0, (sum, item) => sum + (item['total'] as double));
  }

  double get _grandTotal => _autoGeneratedTotal + _manualTotal;

  void _generateAutoBudget() {
    try {
      const budget = {'monto_total': 1000.0};
      setState(() => _autoGeneratedTotal = budget['monto_total'] ?? 0.0);
      HapticFeedback.mediumImpact();
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Presupuesto generado: S/ ${_autoGeneratedTotal.toStringAsFixed(2)}')),
        );
      }
      if (kDebugMode) debugPrint("[TELEMETRIA BUDGET] Presupuesto generado automáticamente: $_autoGeneratedTotal");
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error al generar presupuesto: $e')),
        );
      }
      if (kDebugMode) debugPrint("[TELEMETRIA BUDGET] Error en generación automática: $e");
    }
  }

  Future<void> _exportToExcel() async {
    if (_filteredItems.isEmpty && _autoGeneratedTotal == 0) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('No hay datos para exportar')),
      );
      return;
    }

    try {
      var excel = Excel.createExcel();
      Sheet sheet = excel['Presupuesto NTP'];

      sheet.appendRow([
        TextCellValue('Tipo'),
        TextCellValue('Item'),
        TextCellValue('Cantidad'),
        TextCellValue('Precio Unitario'),
        TextCellValue('Total'),
        TextCellValue('Categoría'),
      ]);
      
      if (_autoGeneratedTotal > 0) {
        sheet.appendRow([
          TextCellValue('Automático'),
          TextCellValue('Presupuesto Completo'),
          TextCellValue(''),
          TextCellValue(''),
          DoubleCellValue(_autoGeneratedTotal),
          TextCellValue('NTP'),
        ]);
      }
      
      for (var item in _filteredItems) {
        sheet.appendRow([
          TextCellValue('Manual'),
          TextCellValue(item['item']),
          DoubleCellValue(item['quantity']),
          DoubleCellValue(item['price']),
          DoubleCellValue(item['total']),
          TextCellValue(item['category']),
        ]);
      }
      
      sheet.appendRow([
        TextCellValue('Total'),
        TextCellValue(''),
        TextCellValue(''),
        TextCellValue(''),
        DoubleCellValue(_grandTotal),
        TextCellValue(''),
      ]);

      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/presupuesto_ntp.xlsx');
      await file.writeAsBytes(excel.encode()!);

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Exportado a Excel: ${file.path}')),
      );
      if (kDebugMode) debugPrint("[TELEMETRIA BUDGET] Exportado a Excel");
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error al exportar: $e')),
      );
    }
  }

  void _shareBudget(List<Map<String, dynamic>> items) {
    final text = items.map((item) => '${item['item']} - Cant: ${item['quantity']}, Precio: S/ ${item['price']}, Total: S/ ${item['total']} (${item['category']})').join('\n');
    Share.share('Presupuesto NTP de Proyecto:\nAutomático: S/ ${_autoGeneratedTotal.toStringAsFixed(2)}\nManual: S/ ${_manualTotal.toStringAsFixed(2)}\nGran Total: S/ ${_grandTotal.toStringAsFixed(2)}\nItems:\n$text\nCumple RNC/NTP/RNE.');
    if (kDebugMode) debugPrint("[TELEMETRIA BUDGET] Compartiendo presupuesto NTP");
  }

  @override
  Widget build(BuildContext context) {
    final appState = widget.appState;
    if (appState.plan != 'pro') {
      return const Scaffold(body: Center(child: Text('Esta función es solo para PRO.')));
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Presupuesto PRO - LYP Innova', style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.orange.shade900,
        centerTitle: true,
        actions: [
          PopupMenuButton<String>(
            onSelected: (value) => setState(() => _filterCategory = value == 'Todos' ? null : value),
            itemBuilder: (context) => const [
              PopupMenuItem(value: 'Todos', child: Text('Todas las categorías')),
              PopupMenuItem(value: 'Materiales', child: Text('Materiales')),
              PopupMenuItem(value: 'Mano de Obra', child: Text('Mano de Obra')),
              PopupMenuItem(value: 'Equipos', child: Text('Equipos')),
              PopupMenuItem(value: 'Otros', child: Text('Otros')),
            ],
            icon: const Icon(Icons.filter_list),
            tooltip: 'Filtrar por categoría',
          ),
          IconButton(
            icon: const Icon(Icons.file_download),
            tooltip: 'Exportar a Excel',
            onPressed: _exportToExcel,
          ),
          IconButton(
            icon: const Icon(Icons.share),
            tooltip: 'Compartir presupuesto',
            onPressed: () => _shareBudget(_filteredItems),
          ),
        ],
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final isSmallScreen = constraints.maxWidth < 600;
          return FadeTransition(
            opacity: _fadeAnimation,
            child: Container(
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [Colors.orange.shade50, Colors.white],
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                ),
              ),
              child: Padding(
                padding: EdgeInsets.all(isSmallScreen ? 16.0 : 24.0),
                child: Column(
                  children: [
                    Card(
                      elevation: 8,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          children: [
                            const Text('Generar Presupuesto Automático NTP', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                            const SizedBox(height: 10),
                            ElevatedButton.icon(
                              icon: const Icon(Icons.calculate),
                              label: const Text('Generar con Servicio'),
                              onPressed: _generateAutoBudget,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.orange.shade900,
                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                            ),
                            const SizedBox(height: 10),
                            Text('Total Automático: S/ ${_autoGeneratedTotal.toStringAsFixed(2)}', style: const TextStyle(fontSize: 16, color: Colors.blue)),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),
                    Card(
                      elevation: 8,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          children: [
                            const Text('Agregar Item Manual NTP', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                            const SizedBox(height: 10),
                            TextField(
                              controller: _itemController,
                              decoration: const InputDecoration(
                                labelText: 'Nombre del Item',
                                border: OutlineInputBorder(),
                                prefixIcon: Icon(Icons.build),
                              ),
                            ),
                            const SizedBox(height: 10),
                            Row(
                              children: [
                                Expanded(
                                  child: TextField(
                                    controller: _quantityController,
                                    keyboardType: TextInputType.number,
                                    decoration: const InputDecoration(
                                      labelText: 'Cantidad',
                                      border: OutlineInputBorder(),
                                      prefixIcon: Icon(Icons.numbers),
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 10),
                                Expanded(
                                  child: TextField(
                                    controller: _priceController,
                                    keyboardType: TextInputType.number,
                                    decoration: const InputDecoration(
                                      labelText: 'Precio Unitario',
                                      border: OutlineInputBorder(),
                                      prefixIcon: Icon(Icons.attach_money),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 10),
                            DropdownButtonFormField<String>(
                              initialValue: _selectedCategory,
                              items: const [
                                DropdownMenuItem(value: 'Materiales', child: Text('Materiales')),
                                DropdownMenuItem(value: 'Mano de Obra', child: Text('Mano de Obra')),
                                DropdownMenuItem(value: 'Equipos', child: Text('Equipos')),
                                DropdownMenuItem(value: 'Otros', child: Text('Otros')),
                              ],
                              onChanged: (value) => setState(() => _selectedCategory = value!),
                              decoration: const InputDecoration(
                                labelText: 'Categoría',
                                border: OutlineInputBorder(),
                                prefixIcon: Icon(Icons.category),
                              ),
                            ),
                            const SizedBox(height: 10),
                            ElevatedButton.icon(
                              icon: const Icon(Icons.add),
                              label: const Text('Agregar Item'),
                              onPressed: _addBudgetItem,
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.orange.shade900,
                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),
                    Text(
                      'Total Manual: S/ ${_manualTotal.toStringAsFixed(2)} | Gran Total: S/ ${_grandTotal.toStringAsFixed(2)}',
                      style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.green),
                    ),
                    const SizedBox(height: 10),
                    Expanded(
                      child: _filteredItems.isEmpty
                          ? const Center(child: Text('No hay items manuales. Agrega o genera automáticamente.'))
                          : ListView.builder(
                              itemCount: _filteredItems.length,
                              itemBuilder: (context, index) {
                                final item = _filteredItems[index];
                                return Card(
                                  elevation: 4,
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                                  child: ListTile(
                                    leading: const Icon(Icons.account_balance_wallet, color: Colors.orange),
                                    title: Text(item['item'], style: const TextStyle(fontWeight: FontWeight.bold)),
                                    subtitle: Text('Cant: ${item['quantity']} | Precio: S/ ${item['price']} | Total: S/ ${item['total']} | Cat: ${item['category']}'),
                                    trailing: IconButton(
                                      icon: const Icon(Icons.delete, color: Colors.red),
                                      onPressed: () => _deleteBudgetItem(index),
                                      tooltip: 'Eliminar',
                                    ),
                                  ),
                                );
                              },
                            ),
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}